language: r
os: linux
cache: packages

r:
  - bioc-release
  - bioc-devel

r_packages:
  - covr
bioc_packages:
  - BiocCheck

before_script:
  - R CMD BiocCheck .
after_success:
  - Rscript -e "covr::codecov()"
