language: r
r:
  - bioc-release
  - bioc-devel
sudo: false
cache: packages

r_github_packages:
  - jimhester/lintr
r_packages:
  - covr
bioc_packages:
  - BiocCheck

before_script:
  - R CMD BiocCheck .

after_success:
  - Rscript -e "covr::codecov()"
